# Replace the values below with your actual API keys
PEXELS_API_KEY = "HHeYsyEWsil4kaJUS3GB2WSVLJzfcgbBbJ93rCQBKNH2LOwbNiZ7mCnO"
TTS_API_KEY = "sk_38f6aa9446ebfcc3fd2865f63c33a167bcbd8d3528420330"
VOICE_ID = "j9jfwdrw7BRfcR43Qohk"
